# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 19:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2016, 11, 9, 20, 58, 52, 454000), verbose_name='publication date')),
                ('auto_register', models.BooleanField(default=False)),
                ('confirmation_period', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3)])),
                ('age_minimum', models.IntegerField(default=0)),
                ('attendants', models.ManyToManyField(blank=True, related_name='attending_activities', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(verbose_name='date of birth')),
                ('reg_date', models.DateTimeField(verbose_name='date registered')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time (approx.)')),
                ('place', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alpaca.Activity')),
                ('confirmed_attendants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
