# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 18:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='confirmation_period',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
