# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0002_auto_20161109_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='confirmation_period',
            field=models.IntegerField(default=3),
        ),
    ]
