# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0003_auto_20161110_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 19, 19, 39, 35822), verbose_name='publication date'),
        ),
    ]
