# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0004_auto_20161110_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 19, 36, 8, 897582), verbose_name='publication date'),
        ),
    ]
