# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0005_auto_20161110_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, verbose_name='date of birth'),
        ),
    ]
