# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0007_remove_profile_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
