# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alpaca', '0008_auto_20161110_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pending_attendants',
            field=models.ManyToManyField(blank=True, related_name='waiting_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
