# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0009_activity_pending_attendants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='place',
            new_name='location',
        ),
    ]
