# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0012_auto_20161123_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 10, 57, 27, 586000, tzinfo=utc), verbose_name='date of birth'),
        ),
    ]
