# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0014_auto_20161128_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name_format',
            field=models.CharField(default='nick (full_name)', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_birthday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_real_name',
            field=models.BooleanField(default=True),
        ),
    ]
