# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0017_auto_20161206_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='attendants_count',
            new_name='num_attendants',
        ),
    ]
