# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0018_auto_20161206_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language_preference',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
