# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0019_profile_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
