# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 10:53
from __future__ import unicode_literals

import Alpaca.models
import Alpaca.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0020_profile_current_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cover',
            field=models.ImageField(blank=True, default='no-cover.png', null=True, storage=Alpaca.storage.OverwriteStorage(), upload_to=Alpaca.models.activity_cover_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='no-avatar.png', null=True, storage=Alpaca.storage.OverwriteStorage(), upload_to=Alpaca.models.user_avatar_path),
        ),
    ]
