# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 11:06
from __future__ import unicode_literals

import Alpaca.models
import Alpaca.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0021_auto_20161224_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cover',
            field=models.ImageField(blank=True, default=Alpaca.models.activity_no_cover_path, null=True, storage=Alpaca.storage.OverwriteStorage(), upload_to=Alpaca.models.activity_cover_path),
        ),
    ]
