# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 01:32
from __future__ import unicode_literals

import Alpaca.file_paths
import Alpaca.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alpaca', '0022_auto_20161227_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, default=Alpaca.file_paths.activity_no_cover_path, null=True, storage=Alpaca.storage.OverwriteStorage(), upload_to=Alpaca.file_paths.activity_cover_path)),
                ('banner', models.ImageField(blank=True, default=Alpaca.file_paths.activity_no_cover_path, null=True, storage=Alpaca.storage.OverwriteStorage(), upload_to=Alpaca.file_paths.activity_cover_path)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('city', models.TextField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('num_attendants', models.IntegerField(default=0)),
                ('group_only_attendants', models.BooleanField(default=False)),
                ('allow_any_users', models.BooleanField(default=True)),
                ('auto_register_users', models.BooleanField(default=True)),
                ('auto_register_activities', models.BooleanField(default=False)),
                ('age_minimum', models.IntegerField(default=0)),
                ('attendants', models.ManyToManyField(blank=True, related_name='attending_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='no-logo.png', null=True, storage=Alpaca.storage.OverwriteStorage(), upload_to=Alpaca.file_paths.group_logo_path)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('total_num_members', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('show_email', models.BooleanField(default=True)),
                ('auto_register_users', models.BooleanField(default=False)),
                ('auto_register_activities', models.BooleanField(default=False)),
                ('admin_list', models.ManyToManyField(blank=True, related_name='admin_of', to=settings.AUTH_USER_MODEL)),
                ('member_list', models.ManyToManyField(blank=True, related_name='member_of', to=settings.AUTH_USER_MODEL)),
                ('pending_members', models.ManyToManyField(blank=True, related_name='waiting_groups', to=settings.AUTH_USER_MODEL)),
                ('superuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='author_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='Alpaca.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizing_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_activities',
            field=models.ManyToManyField(blank=True, to='Alpaca.Activity'),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_attendants',
            field=models.ManyToManyField(blank=True, related_name='waiting_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_list', to='Alpaca.Group'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pending_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_activities', to='Alpaca.Group'),
        ),
    ]
