# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0023_auto_20161228_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
